### ISSUE TITLE
Doesn't work on Mac

### ISSUE THREAD

**Issue by FJLopezGarcia** [FDMediagroep/fd-cypress-recorder#91]
The extension is not record anything with a mac or bring up the context menu options, since that involves using "Alt C".

**Comment by willemliu** [comment]
Hi @FJLopezGarcia, thanks for reporting this. Have you tried the alternatives?
![image](https://user-images.githubusercontent.com/974906/93740886-a73e8480-fbeb-11ea-8d42-8c169da9cf88.png)
This description can be found on the bottom of the FD Cypress Recorder popup:
![image](https://user-images.githubusercontent.com/974906/93740927-bb828180-fbeb-11ea-87fa-590e1ae9f543.png)

In case of a Mac I would assume the CTRL should be replaced by CMD?

**Comment by FJLopezGarcia** [comment]
I was able to open the context menu clicking on "ctrl" and right mouse button...
![image](https://user-images.githubusercontent.com/6631983/93992711-29ff4500-fd8e-11ea-8ee7-92bbc99b5b21.png)
![image](https://user-images.githubusercontent.com/6631983/93992943-76e31b80-fd8e-11ea-81e3-f1a801f79426.png)

**Comment by willemliufdmg** [comment]
I'll close this issue as the context menu can be opened on the Mac with the alternative method.
